### ISSUE TITLE
EN locale

### ISSUE THREAD

**Issue by viclafouch** [LoicMahieu/yup-locales#24]
Hello ! 

I'm using React and I let the user to switch from FR to EN, or from EN to FR..

But it looks like I cannot remove the FR locale (without refresh my page).

```ts
import i18n from 'i18next'
import * as yup from 'yup'
import { fr, pt } from 'yup-locales'

export default (): void => {
  const { language } = i18n
  if (language === 'en') {
    yup.setLocale() // HERE HOW I CAN REMOVE FR ? 
  } else if (language === 'fr') {
    yup.setLocale(fr)
  }
}
```

**Comment by LoicMahieu** [comment]
Hi @viclafouch 
Sorry I don't know how to "reset" locale in yup.
I think the best place to ask is directly in the yup repository.

**Comment by Luferov** [comment]
> Seems like the default locale (en) is exported from yup [jquense/yup#814](https://github.com/jquense/yup/issues/814)

this soulution does not work
<img width="425" alt="image" src="https://user-images.githubusercontent.com/26242554/219165923-f5ee0ae3-b505-47ed-9ab7-eb570ef6a249.png">

**Comment by Myzel394** [comment]
@Luferov I think you need to downgrade to v 0.32.11

**Comment by Luferov** [comment]
> @Luferov I think you need to downgrade to version 0.32.11

What about v1?

**Comment by Basaingeal** [comment]
Is there a strong reason not to include the `en` locale? This issue in the `yup` repo (https://github.com/jquense/yup/issues/1910) hasn't gotten a lot of traction, so it's unclear if this solution will ever work again.
