### ISSUE TITLE
Semantic Release?

### ISSUE THREAD

**Issue by cobraz** [LoicMahieu/yup-locales#4]
Hello 👋

I suggest adding [Semantic Release](https://github.com/semantic-release/semantic-release), to make it easier for maintainers to have a full deployment system working that just follows semantic versioning – and with a Probot for [Semantic Pull Requests](https://probot.github.io/apps/semantic-pull-requests/) it can be checked that contributors have added the correct commit messages.

**Comment by LoicMahieu** [comment]
Hi 🤠

It's a good idea. Currently I don't have time for this unfortunately.
Would you be interested to be a collaborator of this repository ? You could review and merge sporadics PR and if you have time, introduce Semantic Release ;)

Thanks!

**Comment by cobraz** [comment]
Sure I can :)

**Comment by cobraz** [comment]
Hi, @LoicMahieu . I'll be closing this now, but if you still want another maintainer, reach out :)
