### ISSUE TITLE
Translating ${path}

### ISSUE THREAD

**Issue by ogenodisho** [LoicMahieu/yup-locales#70]
Hi, I notice that most of the translations include the ${path} template variable. Is it possible for this value to be translatable too? Because currently the path will always be in a single language.

**Comment by ogenodisho** [comment]
Closed because I found a way around the issue.

**Comment by chepe263** [comment]
For future reference, you can use `label('Friendly name')`

```
import * as Yup from "yup"

function rules(){
  return {
    username: Yup.string().required().label("Nombre del usuario")
  }
}
```
